VisionMakers2/VisionMakers2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls, name = 'admin'),
    path('inventory/', include('inventory.urls')),
    path('sales/', include('sales.urls')),
    path('', include('users.urls')),
    path('patients/', include('patients.urls')),
]

VisionMakers2/patients/urls.py
from . import views
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
app_name = 'patients'
urlpatterns = [
    path('select-patient/', views.select_patient, name = 'select_patient'),
    path('view/<pk>/', login_required(views.PatientUpdate.as_view()) , name = 'view_patient'),
    path('vision-rx/<pk>/', views.vision_rx, name = 'vision_rx'),
    path('vision-rx/spectacle-rx/<int:pk>/', login_required(views.SpectacleRxDetail.as_view()), name = 'spectacle-update'),
    path('vision-rx/contact-lens-rx/<int:pk>/', login_required(views.ContactLensRxDetail.as_view()), name = 'contact-lens-update'),
    re_path(r'^vision-rx/spectacle-rx/create/(?P<patient_id>[0-9]+)/$', login_required(views.SpectacleRxCreate.as_view()), name = 'spectacle-create'),
    re_path(r'^vision-rx/contact-lens-rx/create/(?P<patient_id>[0-9]+)/$', login_required(views.ContactLensRxCreate.as_view()), name = 'contact-lens-create'),
    path('insurance-summary/<pk>/', views.insurance_summary, name = 'insurance-summary'),
    path('insurance/med-ins/update/<int:pk>', login_required(views.MedicalInsDetail.as_view()), name = 'med-ins-update'),
    path('insurance/vis-ins/update/<int:pk>', login_required(views.VisionInsDetail.as_view()), name = 'vis-ins-update'),
    path('vision-rx/send-email/<pk>/', views.email_rx, name = 'email-rx'),
]

VisionMakers2/sales/urls.py
from . import views
from django.urls import path
app_name = 'sales'
urlpatterns = [
    

]

VisionMakers2/patients/models.py
from django.db import models
from polymorphic.models import PolymorphicModel
from localflavor.us.models import USStateField, USZipCodeField, USSocialSecurityNumberField
from insurance.models import Insurance
from datetime import date
from django.urls import reverse
class Patient(models.Model):

    '''Name and title'''
    TITLE_CHOICES = (
        ('', '-----'),
        ('Mr.' , 'Mr.'),
        ('Mrs.' , 'Mrs.'),
        ('Ms.' , 'Ms.'),
        ('Dr.', 'Dr.')
    )
    title = models.CharField(max_length = 5, choices =TITLE_CHOICES)
    first = models.CharField(max_length = 40)
    middle = models.CharField(max_length = 1, blank = True)
    last = models.CharField(max_length = 40)
    nickname = models.CharField(max_length = 20, blank = True)
    cos_ptid = models.IntegerField()

    '''Location and address'''
    OFFICE_CHOICES = (
        ('BV' , 'BV'),
        ('WD' , 'WD'),
        ('PA' , 'PA')
    )
    location = models.CharField(max_length = 5, choices = OFFICE_CHOICES)
    address = models.CharField(max_length = 100)
    address2 = models.CharField(max_length = 100, blank = True)
    city = models.CharField(max_length = 40)
    state = USStateField()
    zip = USZipCodeField()

    '''Communication'''
    home_phone = models.CharField(max_length = 25, blank = True)
    work_phone = models.CharField(max_length = 25,  blank = True)
    cell_phone = models.CharField(max_length = 25,  blank = True)

    email = models.EmailField()
    birthdate = models.DateField()
    SSN = USSocialSecurityNumberField()
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other')
    )
    gender = models.CharField(max_length = 5, choices = GENDER_CHOICES)
    student = models.BooleanField()
    notes = models.CharField(max_length = 500, blank = True)
    alert = models.CharField(max_length = 100, blank = True)
    outside_doc = models.CharField(max_length = 50)
    referred_to_doc = models.CharField(max_length = 50)


    def get_absolute_url(self):
        return reverse('patients:view_patient', kwargs={'pk': self.pk})

    def __str__(self):
        return self.first + ' ' + self.middle + ' ' + self.last

    @property
    def age(self):
        '''calculate the age of the person'''
        today = date.today()
        return today.year - self.birthdate.year - ((today.month, today.day) < (self.birthdate.month, self.birthdate.day))

class Common_Rx(PolymorphicModel):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    exam_date = models.DateField()
    expires = models.DateField()
    doctor = models.CharField(max_length = 30)
    notes = models.CharField(max_length = 256)

    class Meta:
        verbose_name_plural = 'Common Rx\'s'

    def __str__(self):
        return self.doctor + ' - ' + self.exam_date

class Spectacle_Rx(Common_Rx):
    od_sphere = models.IntegerField()
    od_cylinder = models.IntegerField()
    od_axis = models.IntegerField()
    od_prism = models.IntegerField()
    od_prism2 = models.IntegerField()
    od_add = models.IntegerField()

    os_sphere = models.IntegerField()
    os_cylinder = models.IntegerField()
    os_axis = models.IntegerField()
    os_prism = models.IntegerField()
    os_prism2 = models.IntegerField()
    os_add = models.IntegerField()

    sv_reading = models.BooleanField()
    sv_distance = models.BooleanField()

    class Meta:
        verbose_name_plural = 'Spectacle Rx\'s'

    def get_absolute_url(self):
        return reverse('patients:spectacle-update', kwargs={'pk': self.pk})

    def __str__(self):
        return super().__str__()

    def class_name(self):
        return 'spectacle'

    def dictionary(self):
        return {
            'od_sphere': self.od_sphere,
            'od_cylinder': self.od_cylinder,
            'od_axis': self.od_axis,
            'od_prism': self.od_prism,
            'od_prism2': self.od_prism2,
            'od_add':self.od_add,
            'os_sphere': self.os_sphere,
            'os_cylinder': self.os_cylinder,
            'os_axis': self.os_axis,
            'os_prism': self.os_prism,
            'os_prism2': self.os_prism2,
            'os_add':self.os_add,
        }

class Contact_Lens_Rx(Common_Rx):
    od_base_curve = models.IntegerField()
    od_power = models.IntegerField()
    od_power2 = models.IntegerField()
    od_ax = models.IntegerField()
    od_diam = models.IntegerField()
    od_add = models.IntegerField()

    os_base_curve = models.IntegerField()
    os_power = models.IntegerField()
    os_power2 = models.IntegerField()
    os_ax = models.IntegerField()
    os_diam = models.IntegerField()
    os_add = models.IntegerField()

    def get_absolute_url(self):
        return reverse('patients:contact-lens-update', kwargs={'pk': self.pk})

    def __str__(self):
        return super().__str__()

    def class_name(self):
        return 'contact-lens'

    def dictionary(self):
        return {
            'od_base_curve': self.od_base_curve,
            'od_power':self.od_power,
            'od_power2':self.od_power2,
            'od_ax':self.od_ax,
            'od_diam':self.od_diam,
            'od_add':self.od_add,
            'os_base_curve':self.os_base_curve,
            'os_power':self.os_power,
            'os_power2':self.os_power2,
            'os_ax':self.os_ax,
            'os_diam':self.os_diam,
            'os_add':self.os_add,
        }

class Patient_Insurance(PolymorphicModel):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    member_id = models.IntegerField()
    plan_name = models.CharField(max_length = 30, blank = True)
    relation_to_insured = models.CharField(
            max_length = 20,
            choices = (
            ('self', 'Self'),
            ('spouse', 'Spouse'),
            ('child', 'Child'),
            ('other', 'Other')
        )
    )
    bill_payer = models.CharField(max_length = 30)
    bp_address1 = models.CharField(max_length = 40)
    bp_address2 = models.CharField(max_length = 40, blank = True)
    bp_city = models.CharField(max_length = 40)
    bp_state = USStateField()
    bp_zip = USZipCodeField()


    class Meta:
        verbose_name_plural = 'Patient Insurances'

    def __str__(self):
        return self.plan_name

class Vision_Ins(Patient_Insurance):
    vision_list = Insurance.objects.all().filter(type = 'vision').values_list('company_name')
    VISION_CHOICES = ()
    for i in range(len(vision_list)):
        VISION_CHOICES = VISION_CHOICES + ((vision_list[i][0], vision_list[i][0]),)
    company_name = models.CharField(max_length = 30, choices = VISION_CHOICES)

    class Meta:
        verbose_name_plural = 'Vision Insurances'

    def __str__(self):
        return self.company_name + ' - ' + super().__str__()

    def class_name(self):
        return 'vision'

    def get_absolute_url(self):
        return reverse('patients:vis-ins-update', kwargs={'pk': self.pk})

class Medical_Ins(Patient_Insurance):
    medical_list = Insurance.objects.all().filter(type = 'medical').values_list('company_name')
    MEDICAL_CHOICES = ()
    for i in range(len(medical_list)):
        MEDICAL_CHOICES = MEDICAL_CHOICES + ((medical_list[i][0], medical_list[i][0]),)
    company_name = models.CharField(max_length = 30, choices = MEDICAL_CHOICES)

    class Meta:
        verbose_name_plural = 'Medical Insurances'

    def class_name(self):
        return 'medical'

    def __str__(self):
        return self.company_name + ' - ' + super().__str__()

    def get_absolute_url(self):
        return reverse('patients:med-ins-update', kwargs={'pk': self.pk})

VisionMakers2/patients/views.py
from django.shortcuts import render
from .filters import PatientFilter
from .models import Patient, Spectacle_Rx, Contact_Lens_Rx, Common_Rx, Vision_Ins, Medical_Ins
from django.views.generic.edit import UpdateView, CreateView
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.views.generic.detail import DetailView
from django.core.mail import send_mail
from django.conf import settings
from django.http import HttpResponse

@login_required
def select_patient(request):
    filter = PatientFilter(request.GET, queryset=Patient.objects.all())
    return render(request, 'patients/select_patient.html', {'filter': filter})

# def view_patient(request, id):
#     patient = Patient.objects.all().get(pk = id)
#     return render(request, 'patients/view_patient.html', {'patient': patient})
@login_required
def vision_rx(request, pk):
    patient = Patient.objects.all().get(pk = pk)
    ordered_rxs = patient.common_rx_set.all().order_by('exam_date')
    return render(request, 'patients/patient_visionrx.html', {'patient': patient})

@login_required
def insurance_summary(request, pk):
    patient = Patient.objects.all().get(pk = pk)
    ordered_rxs = patient.common_rx_set.all().order_by('pk')
    return render(request, 'patients/insurance_summary.html', {'patient': patient})

class PatientUpdate(UpdateView):
    model = Patient
    fields = [
        'cos_ptid',
        'first',
        'middle',
        'last',
        'nickname',
        'gender',
        'address',
        'address2',
        'city',
        'state',
        'zip',
        'location',
        'email',
        'home_phone',
        'cell_phone',
        'work_phone',
        'birthdate',
        'student',
        'SSN',
        'notes',
        'alert',
        'outside_doc',
        'referred_to_doc',
    ]
    template_name_suffix = '_profile'

    # class Spectacle_Rx_Update(UpdateView):
    #     model = Spectacle_Rx
    #     fields = [
    #
    #     ]

class SpectacleRxDetail(UpdateView):
    template_name = 'patients/spectacle_rx_update.html'
    model = Spectacle_Rx
    fields = [
        'exam_date',
        'expires',
        'doctor',
        'notes',
        'od_sphere',
        'od_cylinder',
        'od_axis',
        'od_prism',
        'od_prism2',
        'od_add',
        'os_sphere',
        'os_cylinder',
        'os_axis',
        'os_prism',
        'os_prism2',
        'os_add',
        'sv_reading',
        'sv_distance',
    ]
    def get_context_data(self, **kwargs):
        context = super(SpectacleRxDetail, self).get_context_data(**kwargs)
        patient = self.object.patient
        context['patient'] = patient
        return context

class ContactLensRxDetail(UpdateView):
    template_name = 'patients/contact_lens_rx_update.html'
    model = Contact_Lens_Rx
    fields = [
        'exam_date',
        'expires',
        'doctor',
        'notes',
        'od_base_curve',
        'od_power',
        'od_power2',
        'od_ax',
        'od_diam',
        'od_add',
        'os_base_curve',
        'os_power',
        'os_power2',
        'os_ax',
        'os_diam',
        'os_add',
    ]
    def get_context_data(self, **kwargs):
        context = super(ContactLensRxDetail, self).get_context_data(**kwargs)
        patient = self.object.patient
        context['patient'] = patient
        return context

class SpectacleRxCreate(CreateView):
    template_name = 'patients/spectacle_rx_update.html'
    model = Spectacle_Rx
    fields = [
        'exam_date',
        'expires',
        'doctor',
        'notes',
        'od_sphere',
        'od_cylinder',
        'od_axis',
        'od_prism',
        'od_prism2',
        'od_add',
        'os_sphere',
        'os_cylinder',
        'os_axis',
        'os_prism',
        'os_prism2',
        'os_add',
        'sv_reading',
        'sv_distance',
    ]


    def get_context_data(self, **kwargs):
        context = super(SpectacleRxCreate, self).get_context_data(**kwargs)
        patient = Patient.objects.all().get(pk = self.kwargs['patient_id'])
        context['patient'] = patient
        context['create'] = True
        return context

    def form_valid(self, form):
        form.instance.patient = Patient.objects.all().get(pk=self.kwargs['patient_id'])
        return super().form_valid(form)


class ContactLensRxCreate(CreateView):
    template_name = 'patients/contact_lens_rx_update.html'
    model = Contact_Lens_Rx
    fields = [
        'exam_date',
        'expires',
        'doctor',
        'notes',
        'od_base_curve',
        'od_power',
        'od_power2',
        'od_ax',
        'od_diam',
        'od_add',
        'os_base_curve',
        'os_power',
        'os_power2',
        'os_ax',
        'os_diam',
        'os_add',
    ]
    def get_context_data(self, **kwargs):
        context = super(ContactLensRxCreate, self).get_context_data(**kwargs)
        patient = Patient.objects.all().get(pk = self.kwargs['patient_id'])
        context['patient'] = patient
        context['create'] = True
        return context

    def form_valid(self, form):
        form.instance.patient = Patient.objects.all().get(pk=self.kwargs['patient_id'])
        return super().form_valid(form)

class MedicalInsDetail(UpdateView):
    template_name = 'patients/insurance_medical_detail.html'
    model = Medical_Ins
    fields = [
        'member_id',
        'company_name',
        'plan_name',
        'relation_to_insured',
        'bill_payer',
        'bp_address1',
        'bp_address2',
        'bp_city',
        'bp_state',
        'bp_zip',
    ]
    def get_context_data(self, **kwargs):
        context = super(MedicalInsDetail, self).get_context_data(**kwargs)
        patient = self.object.patient
        context['patient'] = patient
        return context

class VisionInsDetail(UpdateView):
    template_name = 'patients/insurance_vision_detail.html'
    model = Vision_Ins
    fields = [
        'member_id',
        'company_name',
        'plan_name',
        'relation_to_insured',
        'bill_payer',
        'bp_address1',
        'bp_address2',
        'bp_city',
        'bp_state',
        'bp_zip',
    ]
    def get_context_data(self, **kwargs):
        context = super(VisionInsDetail, self).get_context_data(**kwargs)
        patient = self.object.patient
        context['patient'] = patient
        return context

@login_required
def email_rx(request, pk):
    rx = Common_Rx.objects.all().get(pk = pk)
    if rx.class_name() is 'spectacle':
        type = 'Spectacle'
    else:
        type = 'Contact Lens'
    message = ''
    dict = rx.dictionary()
    for key, value in dict.items():
        message += key + ' - ' + str(value) + '\n'
    print(message)
    send_mail(
        subject = type + ' Rx',
        message = message,
        from_email= settings.EMAIL_HOST_USER,
        recipient_list=['cboham10@gmail.com'],
    )
    return HttpResponse('I think the email sent')

VisionMakers2/patients/templates/patients/contact_lens_rx_update.html
{% extends 'patients/patient_template.html' %}

{% block content %}
<div class="col-md-10">
  <div class="card" id = "patient-card">
    <div class="card-body">
      <div class="row">
        <div class="col-md-12 patient-header">
          <h3>{{patient.first|capfirst}} {{patient.middle|capfirst}} {{patient.last|capfirst}} ID: {{patient.id}},
            Age: {{patient.age}},   Contact Lens Rx
            {% if not create %}
            , Date: {{object.exam_date|date:"m/d/y"}}
            {% endif %}
          </h3>
          <hr>
          <div class="row">
            <span style = "color:red;">{{form.errors}}</span>
            <form  method = "post">
              <div class="col-md-3 padded">
                {% csrf_token%}
                {% for item in form %}
                {% if forloop.counter is 5 %}
              </div>
              <div class="col-md-3 padded">
                {% endif %}
                {% if forloop.counter is 9 %}
              </div>
              <div class="col-md-3 padded">
                {% endif %}
                {% if forloop.counter is 13 %}
              </div>
              <div class="col-md-3 padded">
                {% endif %}
                <div class="form-group row">
                  <label for="{{item.label}}" class="col-4 col-form-label">{{item.label}}</label>
                  <div class="col-8">
                    <!-- <input id="{{item.label}}" name="{{item.label}}" value="{{item.value}}" class="form-control here" type="text"> -->
                    {{item}}
                  </div>
                </div>
                {% endfor %}
              </div>


            </div>
            <div class="row">
              <div class="col-md-3 padded">
              <div class="form-group row">
                <div class="offset-4 col-8">
                  <input  type="submit" value = "Update" class="btn btn-primary"></input>
                  {% if not create %}
                    <a href="#" class = 'btn btn-primary btn-md' >Print</a>
                    <a href="{% url 'patients:email-rx' object.pk %}" class = 'btn btn-primary btn-md' >Email</a>
                  {% endif %}
                </div>
              </div>
            </div>
            </div>
          </form>
          </div>
        </div>
      </div>






        </div>
      </div>

    </div>
  </div>
</div>
</div>
</div>
{% endblock %}

VisionMakers2/patients/templates/patients/insurance_medical_detail.html
{% extends 'patients/patient_template.html' %}

{% block content %}
<div class="col-md-10">
  <div class="card" id = "patient-card">
    <div class="card-body">
      <div class="row">
        <div class="col-md-12 patient-header">
          <h3>{{patient.first|capfirst}} {{patient.middle|capfirst}} {{patient.last|capfirst}} ID: {{patient.id}},
            Age: {{patient.age}},   Spectacle, Date: {{object.exam_date|date:"m/d/y"}}
          </h3>
          <hr>
          <div class="row">
            <span style = "color:red;">{{form.errors}}</span>
            <form  method = "post">
              <div class="col-md-3 padded">
                {% csrf_token%}
                {% for item in form %}
                {% if forloop.counter is 6 %}
              </div>
              <div class="col-md-3 padded">
                {% endif %}
                {% if forloop.counter is 11 %}
              </div>
              <div class="col-md-3 padded">
                {% endif %}
                {% if forloop.counter is 16 %}
              </div>
              <div class="col-md-3 padded">
                {% endif %}
                <div class="form-group row">
                  <label for="{{item.label}}" class="col-4 col-form-label">{{item.label}}</label>
                  <div class="col-8">
                    <!-- <input id="{{item.label}}" name="{{item.label}}" value="{{item.value}}" class="form-control here" type="text"> -->
                    {{item}}
                  </div>
                </div>
                {% endfor %}
              </div>


            </div>
            <div class="row">
              <div class="col-md-3 padded">
              <div class="form-group row">
                <div class="offset-4 col-8">
                  <input  type="submit" value = "Update" class="btn btn-primary"></input>
                  {% if not create %}
                  <a href="#" class = 'btn btn-primary btn-md' >Print</a>
                  <a href="#" class = 'btn btn-primary btn-md' >Email</a>
                  {% endif %}
                </div>
              </div>
            </div>
            </div>
          </form>
          </div>

        </div>
      </div>





        </div>
      </div>

    </div>
  </div>
</div>
</div>
</div>
{% endblock %}

VisionMakers2/patients/templates/patients/insurance_summary.html
{% extends 'patients/patient_template.html' %}

{% block content %}
<div class="col-md-10">
  <div class="card" id = "patient-card">
    <div class="card-body">
      <div class="row">
        <div class="col-md-12 patient-header">
          <h4>{{patient.first|capfirst}} {{patient.middle|capfirst}} {{patient.last|capfirst}} ID: {{patient.id}}</h4>

        </div>

        <!-- table for the rx's -->
        <table class = "table">
          <tr>
            <th>Insurance</th>
            <th>Type</th>
            <th>Company</th>
            <th>Plan Name</th>
            <th></th>
          </tr>
            {% for insurance in patient.patient_insurance_set.all %}
          <tr>
            <td>{{forloop.counter}}</td>
            {% if 'edical' in insurance.class_name %}
            <td>Medical</td>
            {% else %}
            <td>Vision</td>
            {% endif %}
            <td>{{insurance.company_name}}</td>
            <td>{{insurance.plan_name}}</td>
            <td>
              {% if 'edical' in insurance.class_name %}
              <a href="{% url 'patients:med-ins-update' patient.pk %}">Details/Edit</a>
              {% else %}
              <a href="{% url 'patients:vis-ins-update' patient.pk %}">Details/Edit</a>
              {% endif %}
            </td>
        </tr>
            {% endfor %}


          </tr>
        </table>
      </div>
      <div class="row">
        <div class="col-md-3 padded">
        <div class="form-group row">
          <div class="offset-4 col-8">
            <a href="#" class = "btn btn-primary btn-sm">Add Insurance</a>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>


</div>
{% endblock %}

VisionMakers2/patients/templates/patients/insurance_vision_detail.html
{% extends 'patients/patient_template.html' %}

{% block content %}
<div class="col-md-10">
  <div class="card" id = "patient-card">
    <div class="card-body">
      <div class="row">
        <div class="col-md-12 patient-header">
          <h3>{{patient.first|capfirst}} {{patient.middle|capfirst}} {{patient.last|capfirst}} ID: {{patient.id}},
            Age: {{patient.age}},   Spectacle, Date: {{object.exam_date|date:"m/d/y"}}
          </h3>
          <hr>
          <div class="row">
            <span style = "color:red;">{{form.errors}}</span>
            <form  method = "post">
              <div class="col-md-3 padded">
                {% csrf_token%}
                {% for item in form %}
                {% if forloop.counter is 6 %}
              </div>
              <div class="col-md-3 padded">
                {% endif %}
                {% if forloop.counter is 11 %}
              </div>
              <div class="col-md-3 padded">
                {% endif %}
                {% if forloop.counter is 16 %}
              </div>
              <div class="col-md-3 padded">
                {% endif %}
                <div class="form-group row">
                  <label for="{{item.label}}" class="col-4 col-form-label">{{item.label}}</label>
                  <div class="col-8">
                    <!-- <input id="{{item.label}}" name="{{item.label}}" value="{{item.value}}" class="form-control here" type="text"> -->
                    {{item}}
                  </div>
                </div>
                {% endfor %}
              </div>


            </div>
            <div class="row">
              <div class="col-md-3 padded">
              <div class="form-group row">
                <div class="offset-4 col-8">
                  <input  type="submit" value = "Update" class="btn btn-primary"></input>
                  {% if not create %}
                  <a href="#" class = 'btn btn-primary btn-md' >Print</a>
                  <a href="#" class = 'btn btn-primary btn-md' >Email</a>
                  {% endif %}
                </div>
              </div>
            </div>
            </div>
          </form>
          </div>

        </div>
      </div>





        </div>
      </div>

    </div>
  </div>
</div>
</div>
</div>
{% endblock %}

VisionMakers2/patients/templates/patients/patient_template.html
<!DOCTYPE html>

{% extends 'sales/base.html' %}

{% block body %}
<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky" >
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'patients:view_patient' patient.pk %}">
              <span data-feather="home"></span>
              Patient Profile <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'patients:vision_rx' patient.pk %}">
              <span data-feather="file"></span>
              Vision RX
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="shopping-cart"></span>
              Create Order
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'patients:insurance-summary' patient.pk %}">
              <span data-feather="umbrella"></span>
              Insurance
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Integrations
            </a>
          </li>
        </ul>
<!--
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="d-flex align-items-center text-muted" href="#">
            <span data-feather="plus-circle"></span>
          </a>
        </h6> -->
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>

        </ul>
      </div>
    </nav>

    {% block content %}


    {% endblock %}
      </div>
    </div>
  </div>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="../../assets/js/vendor/popper.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>

<!-- Icons -->
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
feather.replace()
</script>


{% endblock %}

VisionMakers2/patients/templates/patients/patient_visionrx.html
{% extends 'patients/patient_template.html' %}
{% block content %}
<div class="col-md-10">
  <div class="card" id = "patient-card">
    <div class="card-body">
      <div class="row">
        <div class="col-md-12 patient-header">
          <h4>{{patient.first|capfirst}} {{patient.middle|capfirst}} {{patient.last|capfirst}} ID: {{patient.id}}</h4>

        </div>

        <!-- table for the rx's -->
        <table class = "table">
          <tr>
            <th>Prescription Type</th>
            <th>Optometrist</th>
            <th>Rx Date</th>
            <th></th>
            {% for rx in patient.common_rx_set.all %}
          </tr>
              {% if rx.od_sphere %}
            <td>Spectacle</td>
              {% else %}
            <td>Contact Lenses</td>
              {% endif %}
            <td>{{rx.doctor}}</td>
            <td>{{rx.exam_date|date:"m/d/y"}}</td>
            {% if rx.od_sphere %}
            <td><a href = "{% url 'patients:spectacle-update' rx.id %}" >Edit/Details</a></td>
            {% else %}
            <td><a href = "{% url 'patients:contact-lens-update' rx.id %}" >Edit/Details</a></td>
            {% endif %}
          <!-- for rx in patient -->
          <tr>
            {% endfor %}


          </tr>
        </table>
        <div class="container col-md-4" id = 'buttoncontainer' style = "margin-bottom:4px;">
          <a href="{% url 'patients:spectacle-create' patient_id=patient.pk %}" class = 'btn btn-primary btn-md' >Add Spectacle Rx</a>
          <a href="{% url 'patients:contact-lens-create' patient_id=patient.pk %}" class = 'btn btn-primary btn-md' >Add Contact Lens Rx</a>

        </div>
      </div>
    </div>
  </div>


</div>
{% endblock %}