VisionMakers2/VisionMakers2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls, name = 'admin'),
    path('inventory/', include('inventory.urls')),
    path('sales/', include('sales.urls')),
    path('', include('users.urls')),
    path('patients/', include('patients.urls')),
]

VisionMakers2/inventory/urls.py
from . import views
from django.urls import path
from django.contrib.auth.decorators import login_required

app_name = 'inventory'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('new-frame/add/', login_required(views.TypeCreate.as_view()), name = 'add-type'),
    path('existing-frame/add/', views.pair_create, name = 'add-pair'),
    path('frame-type/<int:pk>/', login_required(views.DetailView.as_view()), name = 'detail-type'),
    path('frame-type/<int:pk>/edit/', login_required(views.TypeUpdate.as_view()), name = 'edit-type'),
    path('frame-type/<int:pk>/delete/', login_required(views.TypeDelete.as_view()), name = 'delete-type'),
    path('frame-type/<int:pk>/print/', views.print_page, name = 'print-type'),
    path('search/', views.search, name = 'search'),
    path('search/multiupdate/<skus>', views.multiupdate, name = 'multiupdate'),
    path('submitted/', views.submission, name = 'submission'),
    path('export/xls/<location>/<title>', views.export_to_xls, name = 'export_to_xls'),
    path('export/', views.get_export, name = 'export'),

]

VisionMakers2/patients/urls.py
from . import views
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
app_name = 'patients'
urlpatterns = [
    path('select-patient/', views.select_patient, name = 'select_patient'),
    path('view/<pk>/', login_required(views.PatientUpdate.as_view()) , name = 'view_patient'),
    path('vision-rx/<pk>/', views.vision_rx, name = 'vision_rx'),
    path('vision-rx/spectacle-rx/<int:pk>/', login_required(views.SpectacleRxDetail.as_view()), name = 'spectacle-update'),
    path('vision-rx/contact-lens-rx/<int:pk>/', login_required(views.ContactLensRxDetail.as_view()), name = 'contact-lens-update'),
    re_path(r'^vision-rx/spectacle-rx/create/(?P<patient_id>[0-9]+)/$', login_required(views.SpectacleRxCreate.as_view()), name = 'spectacle-create'),
    re_path(r'^vision-rx/contact-lens-rx/create/(?P<patient_id>[0-9]+)/$', login_required(views.ContactLensRxCreate.as_view()), name = 'contact-lens-create'),
    path('insurance-summary/<pk>/', views.insurance_summary, name = 'insurance-summary'),
    path('insurance/med-ins/update/<int:pk>', login_required(views.MedicalInsDetail.as_view()), name = 'med-ins-update'),
    path('insurance/vis-ins/update/<int:pk>', login_required(views.VisionInsDetail.as_view()), name = 'vis-ins-update'),
    path('vision-rx/send-email/<pk>/', views.email_rx, name = 'email-rx'),
]

VisionMakers2/sales/urls.py
from . import views
from django.urls import path
app_name = 'sales'
urlpatterns = [
    

]

VisionMakers2/users/urls.py
from . import views
from django.urls import path
app_name = 'users'
urlpatterns = [
    path('register/', views.create_profile, name = 'register'),
    path('index/', views.index, name = 'index'),
    path('', views.user_login, name = 'home'),
    path('login/', views.user_login, name = 'login'),
    path('logout/', views.user_logout, name = 'logout'),

]

VisionMakers2/inventory/forms.py
from django import forms
from .models import Type


class ExportForm(forms.Form):
    OFFICE_CHOICES = (
        ('Beavercreek' , 'Beavercreek'),
        ('Woodman' , 'Woodman'),
        ('Pittsburgh' , 'Pittsburgh'),
        ('All Locations', 'All Locations')
        )
    location = forms.ChoiceField(choices = OFFICE_CHOICES)
    file_name = forms.CharField(max_length = 50)

    def clean_file_name(self):
        file_name = self.cleaned_data['file_name']
        if ' ' in file_name:
            raise forms.ValidationError('Do not include spaces in the file name')
        return file_name

class PairForm(forms.Form):
    type_list = Type.objects.all().order_by().values_list('sku')
    TYPE_CHOICES = ()
    for i in range(len(type_list)):
        #very obnoxious code that I can't figure out a way around
        TYPE_CHOICES = TYPE_CHOICES + ((type_list[i][0], type_list[i][0]),)
    type = forms.ChoiceField(choices = TYPE_CHOICES)

    OFFICE_CHOICES = (
        ('BV' , 'BV'),
        ('WD' , 'WD'),
        ('PA' , 'PA')
        )
    location = forms.ChoiceField(choices = OFFICE_CHOICES)
    comments = forms.CharField(required = False)
    date_added = forms.DateField()

# class TypeForm(forms.Form):
#     sku = forms.IntegerField()
#     vendor = forms.CharField(max_length = 30)
#     comments = forms.CharField(widget = forms.Textarea, required = False)
#     color = forms.CharField(max_length = 30)
#     STYLE_CHOICES = (
#         ('M' , 'Men\'s'),
#         ('W' , 'Women\'s')
#     )
#     style = forms.ChoiceField(choices = STYLE_CHOICES)
#     desc = forms.CharField(max_length = 30)
#     '''price data'''
#     VID = forms.IntegerField()
#     HCFA = forms.CharField(max_length = 30, initial = 'V2020')
#     wholesale = forms.FloatField()
#     retail = forms.FloatField()
#     cost = forms.FloatField()
#     taxable = forms.BooleanField(required = False)
#
#     '''stock data'''
#     on_hand = forms.IntegerField(initial = 0)
#     on_order = forms.IntegerField(initial = 0)
#     reorder_point = forms.IntegerField(initial = 0)
#     lead_time = forms.IntegerField(initial = 0)
#
#     '''measurements'''
#     eye = forms.IntegerField(initial = 15)
#     bridge = forms.IntegerField(initial = 15)
#     temple = forms.IntegerField(initial = 15)
#     A = forms.IntegerField(initial = 15)
#     B = forms.IntegerField(initial = 15)
#     ED = forms.IntegerField(initial = 15)
#     DBL = forms.IntegerField(initial = 15)
#     size = forms.CharField(max_length = 10)
#
#     '''statistics'''
#     sold_this_week = forms.IntegerField(initial = 0)
#     sold_this_month = forms.IntegerField(initial = 0)
#     sold_this_year = forms.IntegerField(initial = 0)

class MultiTypeForm(forms.Form):

    vendor = forms.CharField(max_length = 30, required = False)
    color = forms.CharField(max_length = 30, required = False)
    STYLE_CHOICES = (
        ('', '------'),
        ('M' , 'Men\'s'),
        ('W' , 'Women\'s')
    )
    style = forms.ChoiceField(choices = STYLE_CHOICES, required = False)
    desc = forms.CharField(max_length = 30, required = False)
    '''price data'''
    VID = forms.IntegerField(required = False)
    HCFA = forms.CharField(max_length = 30, required = False)
    wholesale = forms.FloatField(required = False)
    retail = forms.FloatField(required = False)
    cost = forms.FloatField(required = False)
    TAXABLE_CHOICES = (
        ('', '-------'),
        ('yes' , 'Yes'),
        ('no' , 'No')
    )
    taxable = forms.ChoiceField(choices = TAXABLE_CHOICES, required = False)

    '''stock data'''
    on_order = forms.IntegerField(required = False)
    reorder_point = forms.IntegerField(required = False)
    lead_time = forms.IntegerField(required = False)

    '''measurements'''
    eye = forms.IntegerField(required = False)
    bridge = forms.IntegerField(required = False)
    temple = forms.IntegerField(required = False)
    A = forms.IntegerField(required = False)
    B = forms.IntegerField(required = False)
    ED = forms.IntegerField(required = False)
    DBL = forms.IntegerField(required = False)

    comments = forms.CharField(required = False)

VisionMakers2/inventory/views.py
# take a look at existing frame list
# highlight rows on patient search


from django.shortcuts import render, redirect, get_object_or_404
from .models import Type, Pair
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.views import generic
from .filters import TypeFilter
import xlwt
from django.http import HttpResponse
from .forms import ExportForm, MultiTypeForm, PairForm
from django.contrib.auth.decorators import login_required

@login_required()
def index(request):
    inventory = Type.objects.all()
    for item in inventory:
        item.update_on_hand()
    context = {
        'inventory': inventory,
        }
    return render(request, 'inventory/index.html', context)


class DetailView(generic.DetailView):
    template_name = 'inventory/detail.html'
    model = Type

class TypeDelete(DeleteView):
    model = Type
    success_url = reverse_lazy('inventory:index')

class TypeCreate(CreateView):
    model = Type
    fields = [
        'sku',
        'vendor',
        # 'comments',
        'style',
        'desc',
        'VID',
        'HCFA',
        'wholesale',
        'retail',
        'cost',
       'taxable',
       'on_hand',
       'on_order',
       'reorder_point',
       'lead_time',
       'eye',
       'bridge',
       'temple',
       'A',
       'B',
       'ED',
       'DBL',
       'sold_this_week',
       'sold_this_month',
       'sold_this_year',
       'color',
       'comments',

        ]
    success_url = reverse_lazy('inventory:index')

class TypeUpdate(UpdateView):
    model = Type
    fields = [
        'vendor',
        'comments',
        'style',
        'color',
        'desc',
        'VID',
        'HCFA',
        'wholesale',
        'retail',
        'cost',
       'taxable',
       'on_hand',
       'on_order',
       'reorder_point',
       'lead_time',
       'eye',
       'bridge',
       'temple',
       'A',
       'B',
       'ED',
       'DBL',
       'sold_this_week',
       'sold_this_month',
       'sold_this_year',
        ]
    success_url = reverse_lazy('inventory:submission')


def pair_create(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        form = PairForm(request.POST)
        # check whether it's valid:

        if form.is_valid():
            # process the data in form.cleaned_data as required
            currentObj = Type.objects.all().get(pk = form.cleaned_data['type'])
            pair = Pair(
                type = currentObj,
                location = form.cleaned_data['location'],
                date_added = form.cleaned_data['date_added'],
                comments = form.cleaned_data['comments']
            )
            pair.save()
            currentObj.pair_set.add(pair)
            currentObj.save()
            # redirect to a new URL:
            return redirect('inventory:submission')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PairForm()

    return render(request, 'inventory/pair-form.html', {'form': form})

@login_required
def  print_page(request, pk):
    obj = get_object_or_404(Type, pk = pk)

    return render(request, 'inventory/print.html', {'item': obj})

@login_required
def search(request):
    type_filter = TypeFilter(request.GET, queryset=Type.objects.all())
    return render(request, 'inventory/filter.html', {'filter': type_filter})


@login_required
def submission(request):
    return render(request, 'inventory/submission.html')


@login_required
def export_to_xls(request, location, title):

    response = HttpResponse(content_type = 'application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename = "' + title + '.xls"'

    wb = xlwt.Workbook(encoding = 'utf-8')
    ws = wb.add_sheet(title)

    #Sheet header, first row
    row_num = 0
    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    ws.write(row_num, 0, location.title(), font_style)
    row_num += 2
    columns = ['SKU', 'Vendor', 'Desc', 'Style', 'Color', 'Size', 'Cost', 'Retail', 'On Hand']

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    #Sheet Body, remaining rows
    font_style = xlwt.XFStyle()

    inventory = Type.objects.all()
    for item in inventory:
        item.update_on_hand()
    if location.lower() == 'all locations':
        rows = Type.objects.all().values_list('sku', 'vendor', 'desc', 'style', 'color', 'eye','cost', 'retail', 'on_hand')
        for row in rows:
            row_num += 1

            for col_num in range(len(row)):
                if columns[col_num] == 'Size':
                    ws.write(row_num, col_num, Type.objects.all().get(pk = row[0]).size(), font_style)
                else:
                    ws.write(row_num, col_num, row[col_num], font_style)

    elif location.lower() == 'beavercreek':
        rows = Type.objects.all().values_list('sku', 'vendor', 'desc', 'style', 'color', 'eye','cost', 'retail', 'on_hand')
        for row in rows:
            row_num += 1

            for col_num in range(len(row)):
                if columns[col_num] == 'On Hand':
                    ws.write(row_num, col_num, Type.objects.all().get(pk = row[0]).get_stock_bv())
                elif columns[col_num] == 'Size':
                    ws.write(row_num, col_num, Type.objects.all().get(pk = row[0]).size(), font_style)
                else:
                    ws.write(row_num, col_num, row[col_num], font_style)
    elif location.lower() == 'woodman':
        rows = Type.objects.all().values_list('sku', 'vendor', 'desc', 'style', 'color', 'eye','cost', 'retail', 'on_hand')
        for row in rows:
            row_num += 1

            for col_num in range(len(row)):
                if columns[col_num] == 'On Hand':
                    ws.write(row_num, col_num, Type.objects.all().get(pk = row[0]).get_stock_wd())
                elif columns[col_num] == 'Size':
                    ws.write(row_num, col_num, Type.objects.all().get(pk = row[0]).size(), font_style)
                else:
                    ws.write(row_num, col_num, row[col_num], font_style)
    elif location.lower() == 'pittsburgh':
        rows = Type.objects.all().values_list('sku', 'vendor', 'desc', 'style', 'color', 'eye','cost', 'retail', 'on_hand')
        for row in rows:
            row_num += 1

            for col_num in range(len(row)):
                if columns[col_num] == 'On Hand':
                    ws.write(row_num, col_num, Type.objects.all().get(pk = row[0]).get_stock_pa())
                elif columns[col_num] == 'Size':
                    ws.write(row_num, col_num, Type.objects.all().get(pk = row[0]).size(), font_style)
                else:
                    ws.write(row_num, col_num, row[col_num], font_style)
    wb.save(response)
    return response

@login_required
def get_export(request):

    if request.method == 'POST':
        form = ExportForm(request.POST)
        if form.is_valid():
            return render(request, 'inventory/export.html', { 'location': form.cleaned_data['location'],
                                                            'file_name': form.cleaned_data['file_name'],
                                                            })
    else:
        form = ExportForm()

    return render(request, 'inventory/export.html', {'form': form})

def multiupdate(request, skus):
    skus_list = skus.split("_")

    if request.method == 'POST':

        form = MultiTypeForm(request.POST)
        if form.is_valid():
            for sku in skus_list:
                #make changes in all of the skus
                currentObj = Type.objects.get(pk = sku)
                for key in form.cleaned_data:

                    if key == "vendor" and form.cleaned_data[key] != '':
                        currentObj.vendor = form.cleaned_data[key]
                    elif key == "color" and form.cleaned_data[key] != '':
                        currentObj.color = form.cleaned_data[key]
                    elif key == "HCFA" and form.cleaned_data[key] != '':
                        currentObj.HCFA = form.cleaned_data[key]
                    elif key == "taxable" :
                        if form.cleaned_data[key] == 'yes':
                            currentObj.taxable = True
                        elif form.cleaned_data[key] == 'no':
                            currentObj.taxable = False
                    elif key == "eye" and form.cleaned_data[key] is not None:
                        currentObj.eye = form.cleaned_data[key]
                    elif key == "B" and form.cleaned_data[key] is not None:
                        currentObj.B = form.cleaned_data[key]
                    elif key == "comments" and form.cleaned_data[key] != '':
                        currentObj.comments = form.cleaned_data[key]
                    elif key == "style" and form.cleaned_data[key] != '':
                        currentObj.style = form.cleaned_data[key]
                    elif key == "wholesale" and form.cleaned_data[key] is not None:
                        currentObj.wholesale = form.cleaned_data[key]
                    elif key == "on_order" and form.cleaned_data[key] is not None:
                        currentObj.on_order = form.cleaned_data[key]
                    elif key == "bridge" and form.cleaned_data[key] is not None:
                        currentObj.bridge = form.cleaned_data[key]
                    elif key == "ED" and form.cleaned_data[key] is not None:
                        currentObj.ED = form.cleaned_data[key]
                    elif key == "desc" and form.cleaned_data[key] != '':
                        currentObj.desc = form.cleaned_data[key]
                    elif key == "retail" and form.cleaned_data[key] is not None:
                        currentObj.retail = form.cleaned_data[key]

VisionMakers2/inventory/templates/inventory/base.html
<!DOCTYPE html>
<html lang = "en">
<head>
	<meta charset = "UTF-8">
	<title>{% block title %}VisionMakers{% endblock %}</title>

	{% load static %}
<link rel = "stylesheet" type = "text/css" href = "{% static "inventory/style.css" %}" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<link href = 'https://fonts.googleapis.com/css?family=Satisfy' rel = 'stylesheet' type = 'text/css'/>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


</head>
{% if close %}
<body onload ="myFunction()">
{% else %}
<body>
{% endif %}

<nav id = "navbar" class = "navbar navbar-inverse">
	<div class = "container-fluid">

		<!--  Header -->
		<div class = "navbar-header">
			<button type = "button" class = "navbar-toggle" data-toggle = "collapse" data-target = "#topNavBar">
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
			</button>
			<a class = "navbar-brand" href = "{% url 'users:login' %}">VisionMakers</a>
		</div>


		<!-- Items -->
		<div class = "collapse navbar-collapse" id = "topNavBar">
			<ul class = "nav navbar-nav">
				<li class = "active">
					<a href = "{% url 'inventory:index' %}">
						<span class = "glyphicon glyphicon-tag" aria-hidden = "true"></span>&nbsp;
						Inventory
					</a>
				</li>

				<li class = "">
					<a href = "{% url 'patients:select_patient' %}">
						<span class = "glyphicon glyphicon-user" aria-hidden = "true"></span>&nbsp;
						Patient
					</a>
				</li>

				<li class = "">
					<a href = "#">
						<span class = "glyphicon glyphicon-calendar" aria-hidden = "true"></span>&nbsp;
						Calendar
					</a>
				</li>

			</ul>

			<form class = "navbar-form navbar-left" role = "search" method = "get" action = "#">
				{% csrf_token %}
				<div class = "form-group">
					<input type = "text" class = "form-control" name = "q" value = "">
				</div>
				<button type = "submit" class = "btn btn-default"> Search</button>
			</form>

			<ul class = "nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
				<li class = "">
					<a class = "navbar-link" href = "{% url 'users:logout' %}">
						<span class = "glyphicon glyphicon-off" aria-hidden = "true"></span>&nbsp; Logout
					</a>
				</li>
        {% else %}

        <li>
          <a class = "navbar-link" href = "{% url 'users:login' %}">
						<span class = "glyphicon glyphicon-on" aria-hidden = "true"></span>&nbsp; Login
					</a>
        </li>
        {% endif %}

			</ul>

		</div>

	</div>
</nav>

{% block body %}
{% endblock %}


</body>






</html>

VisionMakers2/inventory/templates/inventory/export.html
{% extends 'inventory/base.html' %}
{% load staticfiles %}
{% block title %}Export to Excel{% endblock %}

{% block body %}


  {% if form %}
  <div class="container">
    <div class="jumbotron">
      <h2 class="display-4">Please fill out the form below!</h2>
      <p class="lead">The locations chosen will determine the stock information exported.</p>
      <hr class="my-4">
      <form class = "form" action="{% url 'inventory:export' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input class="btn btn-primary btn-lg" type="submit" value="Submit" />
    <a class="btn btn-info btn-lg" href="{% url 'inventory:index' %}" role="button">Go back to Inventory</a>
    </form>

    </div>
  </div>

  {% else %}

  <div class="container">
    <div class="jumbotron">
      <h2 class="display-4">You can now download your Excel file!</h2>

      <hr class="my-4">
      <p class="lead">
        <a class="btn btn-primary btn-lg" href="{% url 'inventory:export_to_xls' location file_name  %}" role="button">Download</a>
        <a class="btn btn-info btn-lg" href="{% url 'inventory:index' %}" role="button">Go back to Inventory</a>
      </p>
    </div>
  </div>


{% endif %}










{% endblock %}

VisionMakers2/inventory/templates/inventory/form-template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>

	
</head>
<body>



	{% for field in form %}
	<div class = "form-group">
		<div class = "col-sm-offset-2 col-sm-10">
			<span class = "text-danger small">{{ field.errors }}</span>
		</div>
		<label class = "control-label col-sm-2">{{ field.label_tag }}</label>
		<div class = "col-sm-10">{{ field }}
			{% if "ype" in field.label_tag  %}
			<span class = "text-primary medium"><strong>Don't see existing SKU? add, then refresh</strong></span>

			<a href="javascript:window.open('{% url 'inventory:add-type' %}', 'Add Existing Frame', 'width=750,height=600');" class="btn btn-primary btn-xs">

				<span class="glyphicon glyphicon-plus"></span> Add New Frame

			</a>

			{%endif %}
			{% if "date" in field.label_tag  %}
			{# add that date thingy #}
			{%endif %}
		</div>

	</div>

	{% endfor %}
</body>
</html>

VisionMakers2/inventory/templates/inventory/form-template2.html
<br />
<div class="container">
	<div class="row centered-form">
		<div class="col-xs-12 col-sm-12 col-md-12">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title" id = "title">Data Form</h3>
				</div>
				<div class="panel-body">

						<!-- <div class = "row"> -->
							{% for field in form %}

							{{ form.non_field_errors }}


									{% if "ype" in field.label_tag  %}
									<div class="col-xs-6 col-sm-6 col-md-6">
										<div class="form-group" style = "">
											<label>{{field.label_tag}}</label>
											{{ field }}
											{{ field.errors }}
										<span class = "text-primary medium"><strong>Don't see existing SKU? add, then refresh</strong></span>

						   				 <a href="{% url 'inventory:add-type' %}" class="btn btn-primary btn-xs">

						   				 	<span class="glyphicon glyphicon-plus"></span> Add New Frame

						   				 </a>
									{% else %}
									<div class="col-xs-3 col-sm-3 col-md-3">
										<div class="form-group" style = "">
											<label>{{field.label_tag}}</label>
											{{ field }}

									{% endif %}
								</div>
							</div>

							{% endfor %}



						<!-- </div> -->

VisionMakers2/inventory/templates/inventory/multiupdate.html
<!DOCTYPE html>
{% extends 'inventory/base.html' %}
{% load static %}
{% block title %}Update All{% endblock %}
{% block body %}

<form class = "form-horizontal" action = "" method = "post">
  {% csrf_token %}
  {% include 'inventory/form-template2.html' %}
  <div class = "form-group">
    <div class = "col-sm-offset-2 col-sm-10">
      <button class = "btn btn-primary" type = "submit" >Submit</button>
    </div>
  </div>
</form>







{% endblock %}

VisionMakers2/inventory/templates/inventory/pair-form.html
{% extends 'inventory/base.html' %}
{% block title %}  Add Existing Frame {%endblock %}
{% block panel %}<h3>Add Existing Frame </h3> {% endblock %}
{%block body %}

<div class = "container-fluid">
<div class = "row">
<div class = "col-sm-12 col-md-12 col-lg-12">
<div class = "panel panel-default" "style = width: 60%;">
<div class = "panel-body" style="max-height: 500px; ">
	<form class = "form-horizontal" action = "" method = "post">
		{% csrf_token %}
		{% include 'inventory/form-template2.html' %}
		<div class = "form-group">
			<div class = "">
				<button class = "btn btn-primary" style= "float:left;" type = "submit">Submit</button>
			</div>
		</div>
	</form>

</div>
</div>
</div>
</div>
</div>

{% endblock %}

VisionMakers2/inventory/templates/inventory/submission.html
{% extends 'inventory/base.html' %}
{% load staticfiles %}
{% block title %}Submitted{% endblock %}

{% block body %}
<div class="container">


<div class="jumbotron">
  <h1 class="display-4">Your changes have been submitted!</h1>
  <p class="lead">To continue using the inventory, and to see your changes, please refresh the previous page, or you
    may click the link below to open a new inventory page.</p>
  <hr class="my-4">

  <p class="lead">
    <a class="btn btn-primary btn-lg" href="{% url 'inventory:index' %}" role="button">Go to Inventory</a>
  </p>
</div>
</div>
{% endblock %}

VisionMakers2/inventory/templates/inventory/type_form.html
{% load static %}
<link rel = "stylesheet" type = "text/css" href = "{% static "inventory/style.css" %}" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<link href = 'https://fonts.googleapis.com/css?family=Satisfy' rel = 'stylesheet' type = 'text/css'/>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>




	<form class = "form-horizontal" action = "" method = "post">

		{% csrf_token %}
		{% include 'inventory/form-template2.html' %}
		<div class = "form-group">
			<div class = "col-sm-offset-2 col-sm-10">
				<button class = "btn btn-primary" type = "submit" >Submit</button>
			</div>
		</div>
	</form>