VisionMakers2/VisionMakers2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls, name = 'admin'),
    path('inventory/', include('inventory.urls')),
    path('sales/', include('sales.urls')),
    path('', include('users.urls')),
    path('patients/', include('patients.urls')),
]

VisionMakers2/inventory/urls.py
from . import views
from django.urls import path
from django.contrib.auth.decorators import login_required

app_name = 'inventory'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('new-frame/add/', login_required(views.TypeCreate.as_view()), name = 'add-type'),
    path('existing-frame/add/', views.pair_create, name = 'add-pair'),
    path('frame-type/<int:pk>/', login_required(views.DetailView.as_view()), name = 'detail-type'),
    path('frame-type/<int:pk>/edit/', login_required(views.TypeUpdate.as_view()), name = 'edit-type'),
    path('frame-type/<int:pk>/delete/', login_required(views.TypeDelete.as_view()), name = 'delete-type'),
    path('frame-type/<int:pk>/print/', views.print_page, name = 'print-type'),
    path('search/', views.search, name = 'search'),
    path('search/multiupdate/<skus>', views.multiupdate, name = 'multiupdate'),
    path('submitted/', views.submission, name = 'submission'),
    path('export/xls/<location>/<title>', views.export_to_xls, name = 'export_to_xls'),
    path('export/', views.get_export, name = 'export'),

]

VisionMakers2/patients/urls.py
from . import views
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
app_name = 'patients'
urlpatterns = [
    path('select-patient/', views.select_patient, name = 'select_patient'),
    path('view/<pk>/', login_required(views.PatientUpdate.as_view()) , name = 'view_patient'),
    path('vision-rx/<pk>/', views.vision_rx, name = 'vision_rx'),
    path('vision-rx/spectacle-rx/<int:pk>/', login_required(views.SpectacleRxDetail.as_view()), name = 'spectacle-update'),
    path('vision-rx/contact-lens-rx/<int:pk>/', login_required(views.ContactLensRxDetail.as_view()), name = 'contact-lens-update'),
    re_path(r'^vision-rx/spectacle-rx/create/(?P<patient_id>[0-9]+)/$', login_required(views.SpectacleRxCreate.as_view()), name = 'spectacle-create'),
    re_path(r'^vision-rx/contact-lens-rx/create/(?P<patient_id>[0-9]+)/$', login_required(views.ContactLensRxCreate.as_view()), name = 'contact-lens-create'),
    path('insurance-summary/<pk>/', views.insurance_summary, name = 'insurance-summary'),
    path('insurance/med-ins/update/<int:pk>', login_required(views.MedicalInsDetail.as_view()), name = 'med-ins-update'),
    path('insurance/vis-ins/update/<int:pk>', login_required(views.VisionInsDetail.as_view()), name = 'vis-ins-update'),
    path('vision-rx/send-email/<pk>/', views.email_rx, name = 'email-rx'),
]

VisionMakers2/sales/urls.py
from . import views
from django.urls import path
app_name = 'sales'
urlpatterns = [
    

]

VisionMakers2/users/urls.py
from . import views
from django.urls import path
app_name = 'users'
urlpatterns = [
    path('register/', views.create_profile, name = 'register'),
    path('index/', views.index, name = 'index'),
    path('', views.user_login, name = 'home'),
    path('login/', views.user_login, name = 'login'),
    path('logout/', views.user_logout, name = 'logout'),

]

VisionMakers2/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)

    OFFICE_CHOICES = (
        ('BV' , 'BV'),
        ('WD' , 'WD'),
        ('PA' , 'PA')
        )
    location = models.CharField(max_length = 5, choices = OFFICE_CHOICES)
    #additional information
    OCCUPATION_CHOICES = (
        ('DR', 'Doctor'),
        ('R', 'Receptionist'),
        ('O', 'Other')
    )
    occupation = models.CharField(max_length=5, choices = OCCUPATION_CHOICES)

VisionMakers2/users/forms.py
from django.contrib.auth.models import User
from .models import UserProfileInfo
from django import forms
class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password'
            ]


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ['occupation']

VisionMakers2/users/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileForm
from django.urls import reverse,  reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, 'users/index.html')

def create_profile(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'users/register.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered':registered
    })

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("users:home"))

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username = username, password = password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse("users:home"))

            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to login and failed!")
            print("Username: {}".format(username))
            return HttpResponse("invalid login details supplied")

    else:
        return render(request, 'users/login.html', {})

VisionMakers2/users/templates/users/base.html
<!DOCTYPE html>
<html lang = "en">
<head>
	<meta charset = "UTF-8">
	<title>{% block title %}VisionMakers{% endblock %}</title>

	{% load static %}
<link rel = "stylesheet" type = "text/css" href = "{% static "inventory/style.css" %}" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<link href = 'https://fonts.googleapis.com/css?family=Satisfy' rel = 'stylesheet' type = 'text/css'/>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


</head>
{% if close %}
<body onload ="myFunction()">
{% else %}
<body>
{% endif %}

<nav id = "navbar" class = "navbar navbar-inverse">
	<div class = "container-fluid">

		<!--  Header -->
		<div class = "navbar-header">
			<button type = "button" class = "navbar-toggle" data-toggle = "collapse" data-target = "#topNavBar">
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
			</button>
			<a class = "navbar-brand" href = "{% url 'users:login' %}">VisionMakers</a>
		</div>


		<!-- Items -->
		<div class = "collapse navbar-collapse" id = "topNavBar">
			<ul class = "nav navbar-nav">
				<li class = "active">
					<a href = "{% url 'inventory:index' %}">
						<span class = "glyphicon glyphicon-tag" aria-hidden = "true"></span>&nbsp;
						Inventory
					</a>
				</li>

				<li class = "">
					<a href = "#">
						<span class = "glyphicon glyphicon-user" aria-hidden = "true"></span>&nbsp;
						Patient
					</a>
				</li>

				<li class = "">
					<a href = "#">
						<span class = "glyphicon glyphicon-calendar" aria-hidden = "true"></span>&nbsp;
						Calendar
					</a>
				</li>

			</ul>

			<form class = "navbar-form navbar-left" role = "search" method = "get" action = "#">
				{% csrf_token %}
				<div class = "form-group">
					<input type = "text" class = "form-control" name = "q" value = "">
				</div>
				<button type = "submit" class = "btn btn-default"> Search</button>
			</form>



			<ul class = "nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
				<li class = "">
					<a class = "navbar-link" href = "{% url 'users:logout' %}">
						<span class = "glyphicon glyphicon-off" aria-hidden = "true"></span>&nbsp; Logout
					</a>
				</li>
        {% else %}

        <li>
          <a class = "navbar-link" href = "{% url 'users:login' %}">
						<span class = "glyphicon glyphicon-on" aria-hidden = "true"></span>&nbsp; Login
					</a>
        </li>
        {% endif %}
        <li>
          <a class = "navbar-link" href = "{% url 'users:register' %}">
						<span class = "glyphicon glyphicon-pencil" aria-hidden = "true"></span>&nbsp; Register
					</a>
        </li>
			</ul>

		</div>

	</div>
</nav>

{% block body %}
{% endblock %}


</body>






</html>

VisionMakers2/users/templates/users/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/style.css' %}" />
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  </head>
  <body>



    <div class="container">
      <!-- <br/> -->
      <div class="row">
      
        </div>
      </div>

  </body>
</html>

VisionMakers2/users/templates/users/login.html
<!DOCTYPE html>
<html lang = "en">
<head>
	<meta charset = "UTF-8">
	<title>{% block title %}VisionMakers{% endblock %}</title>

	{% load static %}
<link rel = "stylesheet" type = "text/css" href = "{% static "users/style.css" %}" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<link href = 'https://fonts.googleapis.com/css?family=Satisfy' rel = 'stylesheet' type = 'text/css'/>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


</head>
{% if close %}
<body onload ="myFunction()">
{% else %}
<body>
{% endif %}

<nav id = "navbar" class = "navbar navbar-inverse">
	<div class = "container-fluid">

		<!--  Header -->
		<div class = "navbar-header">
			<button type = "button" class = "navbar-toggle" data-toggle = "collapse" data-target = "#topNavBar">
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
			</button>
			<a class = "navbar-brand" href = "{% url 'inventory:index' %}">VisionMakers</a>
		</div>


		<!-- Items -->
		<div class = "collapse navbar-collapse" id = "topNavBar">
			<ul class = "nav navbar-nav">
				<li class = "">
					<a href = "{% url 'inventory:index' %}">
						<span class = "glyphicon glyphicon-tag" aria-hidden = "true"></span>&nbsp;
						Inventory
					</a>
				</li>

				<li class = "">
					<a href = "{% url 'patients:select_patient' %}">
						<span class = "glyphicon glyphicon-user" aria-hidden = "true"></span>&nbsp;
						Patient
					</a>
				</li>

				<li class = "">
          <a href = "#">
            <span class = "glyphicon glyphicon-calendar" aria-hidden = "true"></span>&nbsp;
            Calendar
          </a>
        </li>

      </ul>

      <form class = "navbar-form navbar-left" role = "search" method = "get" action = "#">
        {% csrf_token %}
        <div class = "form-group">
          <input type = "text" class = "form-control" name = "q" value = "">
        </div>
        <button type = "submit" class = "btn btn-default"> Search</button>
      </form>
			<ul class = "nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
				<li class = "">
					<a class = "navbar-link" href = "{% url 'users:logout' %}">
						<span class = "glyphicon glyphicon-off" aria-hidden = "true"></span>&nbsp; Logout
					</a>
				</li>
        {% else %}

        <li>
          <a class = "navbar-link" href = "{% url 'users:register' %}">
						<span class = "glyphicon glyphicon-on" aria-hidden = "true"></span>&nbsp; Register new User
					</a>
        </li>
        {% endif %}

			</ul>
    </div>


  </div>
</nav>

<div class="container">


{% if not user.is_authenticated %}
	<div class="col-md-12">
		<div class="card card-container" >
				<img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />
				<p id="profile-name" class="profile-name-card"></p>
				<form class="form-signin" action="{% url 'users:login' %}" method = "POST">
					{% csrf_token %}
						<span id="reauth-email" class="reauth-email"></span>
						<!-- <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus> -->
		        <input class="form-control" id = "inputEmail" type="text" name="username" placeholder = 'Enter Username'>
						<input type="password" id="inputPassword" class="form-control" name="password" placeholder="Password" required>
						<!-- <div id="remember" class="checkbox">
								<label>
										<input type="checkbox" value="remember-me"> Remember me
								</label>
						</div> -->
						<button class="btn btn-md btn-primary btn-block btn-signin" type="submit">Sign in</button>
				</form><!-- /form -->
				<a href="#" class="forgot-password">
						Forgot the password?
				</a>
		</div><!-- /card-container -->
</div><!-- /container -->
{% else %}


<!-- Small Dashboard, don't really need it yet -->
<!-- <div class="container">
	<div class="row">
			<div class="col-md-6 col-md-offset-3">
					<div class="panel panel-primary">
							<div class="panel-heading">
									<h3 class="panel-title">
											<span class="glyphicon glyphicon-bookmark"></span> Quick Shortcuts</h3>
							</div>
							<div class="panel-body">
									<div class="row">
											<div class="col-xs-6 col-md-6">
												<a href="/admin/" class="btn btn-danger btn-lg btn-panel" role="button"><span class="glyphicon glyphicon-list-alt"></span> <br/>Admin</a>
												<a href="#" class="btn btn-warning btn-lg btn-panel" role="button"><span class="glyphicon glyphicon-bookmark"></span> <br/>Bookmarks</a>
												<a href="#" class="btn btn-primary btn-lg btn-panel" role="button"><span class="glyphicon glyphicon-usd"></span> <br/>Sales</a>
												<a href="#" class="btn btn-primary btn-lg btn-panel" role="button"><span class="glyphicon glyphicon-comment"></span> <br/>Comments</a>
											</div>
											<div class="col-xs-6 col-md-6">
												<a href="#" class="btn btn-success btn-lg btn-panel" role="button"><span class="glyphicon glyphicon-user"></span> <br/>Users</a>
												<a href="#" class="btn btn-info btn-lg btn-panel" role="button"><span class="glyphicon glyphicon-file"></span> <br/>Notes</a>
												<a href="#" class="btn btn-primary btn-lg btn-panel" role="button"><span class="glyphicon glyphicon-picture"></span> <br/>Photos</a>
												<a href="{% url 'inventory:index' %}" class="btn btn-primary btn-lg btn-panel" role="button"><span class="glyphicon glyphicon-tag"></span> <br/>Inventory</a>
											</div>
									</div>
									<a href="http://www.jquery2dotnet.com/" class="btn btn-success btn-lg btn-block" role="button"><span class="glyphicon glyphicon-globe"></span> Website</a>
							</div>
					</div>
			</div>
	</div>
</div> -->

{% endif %}
  <!-- <div class="jumbotron">
    <h2 id = "h2">Please Login</h2>
    <form class="" action="{% url 'users:login' %}" method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder = 'Enter Username'>
      </div>
      <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" name="password">
      </div>


      <input type="submit" name="" value="Login" class = "btn btn-primary btn-lg">

    </form>
  </div> -->
</div>
</body>

VisionMakers2/users/templates/users/register.html
<!DOCTYPE html>
{% extends 'inventory/base.html' %}
{% block title %} Create Profile {% endblock %}
{% block body %}
<div class="container">
  <div class="jumbotron">
    {% if registered %}
    <h1>Thank you for registering!</h1>
    {% else %}
    <h2>Register here!</h2>
    <h3>Please fill out the form:</h3>
    <form class="" action="{% url 'users:register'%}" method="post">
      {% csrf_token %}
      {{ user_form.as_p}}
      {{ profile_form.as_p}}
      <input class = "btn btn-primary btn-md" type="submit" name="" value="Register">
    </form>
    {% endif %}
  </div>
</div>




{% endblock %}